name: Re-run failed workflow

# This workflow CAN NOT be called directly. It is supposed to be called by
# other workflows when they fail and this workflow should trigger a re-run.

on:
  workflow_call:
    inputs:
      run_id:
        required: true
        type: string
  workflow_dispatch:

jobs:
  rerun:
    runs-on: ubuntu-latest
    steps:
      - name: rerun ${{ inputs.run_id }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: |
          gh run watch ${{ inputs.run_id }} > /dev/null 2>&1
          gh run rerun ${{ inputs.run_id }} --failed
